/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _lcmtypes_graph_t_h
#define _lcmtypes_graph_t_h

#ifdef __cplusplus
extern "C" {
#endif

#include "lcmtypes/lcmtypes_vertex_t.h"
#include "lcmtypes/lcmtypes_edge_t.h"
typedef struct _lcmtypes_graph_t lcmtypes_graph_t;
struct _lcmtypes_graph_t
{
    int32_t    num_vertices;
    lcmtypes_vertex_t *vertices;
    int32_t    num_edges;
    lcmtypes_edge_t *edges;
};

lcmtypes_graph_t   *lcmtypes_graph_t_copy(const lcmtypes_graph_t *p);
void lcmtypes_graph_t_destroy(lcmtypes_graph_t *p);

typedef struct _lcmtypes_graph_t_subscription_t lcmtypes_graph_t_subscription_t;
typedef void(*lcmtypes_graph_t_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const lcmtypes_graph_t *msg, void *user);

int lcmtypes_graph_t_publish(lcm_t *lcm, const char *channel, const lcmtypes_graph_t *p);
lcmtypes_graph_t_subscription_t* lcmtypes_graph_t_subscribe(lcm_t *lcm, const char *channel, lcmtypes_graph_t_handler_t f, void *userdata);
int lcmtypes_graph_t_unsubscribe(lcm_t *lcm, lcmtypes_graph_t_subscription_t* hid);
int lcmtypes_graph_t_subscription_set_queue_capacity(lcmtypes_graph_t_subscription_t* subs,
                              int num_messages);


int  lcmtypes_graph_t_encode(void *buf, int offset, int maxlen, const lcmtypes_graph_t *p);
int  lcmtypes_graph_t_decode(const void *buf, int offset, int maxlen, lcmtypes_graph_t *p);
int  lcmtypes_graph_t_decode_cleanup(lcmtypes_graph_t *p);
int  lcmtypes_graph_t_encoded_size(const lcmtypes_graph_t *p);

// LCM support functions. Users should not call these
int64_t __lcmtypes_graph_t_get_hash(void);
int64_t __lcmtypes_graph_t_hash_recursive(const __lcm_hash_ptr *p);
int     __lcmtypes_graph_t_encode_array(void *buf, int offset, int maxlen, const lcmtypes_graph_t *p, int elements);
int     __lcmtypes_graph_t_decode_array(const void *buf, int offset, int maxlen, lcmtypes_graph_t *p, int elements);
int     __lcmtypes_graph_t_decode_array_cleanup(lcmtypes_graph_t *p, int elements);
int     __lcmtypes_graph_t_encoded_array_size(const lcmtypes_graph_t *p, int elements);
int     __lcmtypes_graph_t_clone_array(const lcmtypes_graph_t *p, lcmtypes_graph_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
