/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _lcmtypes_state_t_h
#define _lcmtypes_state_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _lcmtypes_state_t lcmtypes_state_t;
struct _lcmtypes_state_t
{
    double     x;
    double     y;
    double     z;
};

lcmtypes_state_t   *lcmtypes_state_t_copy(const lcmtypes_state_t *p);
void lcmtypes_state_t_destroy(lcmtypes_state_t *p);

typedef struct _lcmtypes_state_t_subscription_t lcmtypes_state_t_subscription_t;
typedef void(*lcmtypes_state_t_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const lcmtypes_state_t *msg, void *user);

int lcmtypes_state_t_publish(lcm_t *lcm, const char *channel, const lcmtypes_state_t *p);
lcmtypes_state_t_subscription_t* lcmtypes_state_t_subscribe(lcm_t *lcm, const char *channel, lcmtypes_state_t_handler_t f, void *userdata);
int lcmtypes_state_t_unsubscribe(lcm_t *lcm, lcmtypes_state_t_subscription_t* hid);
int lcmtypes_state_t_subscription_set_queue_capacity(lcmtypes_state_t_subscription_t* subs,
                              int num_messages);


int  lcmtypes_state_t_encode(void *buf, int offset, int maxlen, const lcmtypes_state_t *p);
int  lcmtypes_state_t_decode(const void *buf, int offset, int maxlen, lcmtypes_state_t *p);
int  lcmtypes_state_t_decode_cleanup(lcmtypes_state_t *p);
int  lcmtypes_state_t_encoded_size(const lcmtypes_state_t *p);

// LCM support functions. Users should not call these
int64_t __lcmtypes_state_t_get_hash(void);
int64_t __lcmtypes_state_t_hash_recursive(const __lcm_hash_ptr *p);
int     __lcmtypes_state_t_encode_array(void *buf, int offset, int maxlen, const lcmtypes_state_t *p, int elements);
int     __lcmtypes_state_t_decode_array(const void *buf, int offset, int maxlen, lcmtypes_state_t *p, int elements);
int     __lcmtypes_state_t_decode_array_cleanup(lcmtypes_state_t *p, int elements);
int     __lcmtypes_state_t_encoded_array_size(const lcmtypes_state_t *p, int elements);
int     __lcmtypes_state_t_clone_array(const lcmtypes_state_t *p, lcmtypes_state_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
