/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _lcmtypes_environment_t_h
#define _lcmtypes_environment_t_h

#ifdef __cplusplus
extern "C" {
#endif

#include "lcmtypes/lcmtypes_region_3d_t.h"
#include "lcmtypes/lcmtypes_region_3d_t.h"
#include "lcmtypes/lcmtypes_region_3d_t.h"
typedef struct _lcmtypes_environment_t lcmtypes_environment_t;
struct _lcmtypes_environment_t
{
    lcmtypes_region_3d_t operating;
    lcmtypes_region_3d_t goal;
    int32_t    num_obstacles;
    lcmtypes_region_3d_t *obstacles;
};

lcmtypes_environment_t   *lcmtypes_environment_t_copy(const lcmtypes_environment_t *p);
void lcmtypes_environment_t_destroy(lcmtypes_environment_t *p);

typedef struct _lcmtypes_environment_t_subscription_t lcmtypes_environment_t_subscription_t;
typedef void(*lcmtypes_environment_t_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const lcmtypes_environment_t *msg, void *user);

int lcmtypes_environment_t_publish(lcm_t *lcm, const char *channel, const lcmtypes_environment_t *p);
lcmtypes_environment_t_subscription_t* lcmtypes_environment_t_subscribe(lcm_t *lcm, const char *channel, lcmtypes_environment_t_handler_t f, void *userdata);
int lcmtypes_environment_t_unsubscribe(lcm_t *lcm, lcmtypes_environment_t_subscription_t* hid);
int lcmtypes_environment_t_subscription_set_queue_capacity(lcmtypes_environment_t_subscription_t* subs,
                              int num_messages);


int  lcmtypes_environment_t_encode(void *buf, int offset, int maxlen, const lcmtypes_environment_t *p);
int  lcmtypes_environment_t_decode(const void *buf, int offset, int maxlen, lcmtypes_environment_t *p);
int  lcmtypes_environment_t_decode_cleanup(lcmtypes_environment_t *p);
int  lcmtypes_environment_t_encoded_size(const lcmtypes_environment_t *p);

// LCM support functions. Users should not call these
int64_t __lcmtypes_environment_t_get_hash(void);
int64_t __lcmtypes_environment_t_hash_recursive(const __lcm_hash_ptr *p);
int     __lcmtypes_environment_t_encode_array(void *buf, int offset, int maxlen, const lcmtypes_environment_t *p, int elements);
int     __lcmtypes_environment_t_decode_array(const void *buf, int offset, int maxlen, lcmtypes_environment_t *p, int elements);
int     __lcmtypes_environment_t_decode_array_cleanup(lcmtypes_environment_t *p, int elements);
int     __lcmtypes_environment_t_encoded_array_size(const lcmtypes_environment_t *p, int elements);
int     __lcmtypes_environment_t_clone_array(const lcmtypes_environment_t *p, lcmtypes_environment_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
