"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

import state_t

class vertex_t(object):
    __slots__ = ["state"]

    def __init__(self):
        self.state = None

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(vertex_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.state._get_packed_fingerprint() == state_t.state_t._get_packed_fingerprint()
        self.state._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != vertex_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return vertex_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = vertex_t()
        self.state = state_t.state_t._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if vertex_t in parents: return 0
        newparents = parents + [vertex_t]
        tmphash = (0x780573746198cdac+ state_t.state_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if vertex_t._packed_fingerprint is None:
            vertex_t._packed_fingerprint = struct.pack(">Q", vertex_t._get_hash_recursive([]))
        return vertex_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

